spring:
  application:
    name: mini-meeting-scheduler
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/minischeduler
    username: minischeduler
    password: minischeduler
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health
