CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email        VARCHAR(320) NOT NULL UNIQUE,
    display_name VARCHAR(120) NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE time_slot
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    start_at TIMESTAMPTZ NOT NULL,
    end_at   TIMESTAMPTZ NOT NULL,
    status   VARCHAR(16) NOT NULL,

    CONSTRAINT time_slot_unique_hour UNIQUE (user_id, start_at),
    CONSTRAINT time_slot_hour_aligned CHECK (start_at = date_trunc('hour', start_at AT TIME ZONE 'UTC') AT TIME ZONE 'UTC'),
    CONSTRAINT time_slot_one_hour_long CHECK (end_at = start_at + INTERVAL '1 hour'),
    CONSTRAINT time_slot_status_valid CHECK (status IN ('FREE', 'BUSY'))
);
