CREATE TABLE meeting
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizer_id BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    title        VARCHAR(200) NOT NULL,
    description  VARCHAR(2000),
    start_at     TIMESTAMPTZ  NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT meeting_hour_aligned CHECK (start_at = date_trunc('hour', start_at AT TIME ZONE 'UTC') AT TIME ZONE 'UTC')
);

ALTER TABLE time_slot
    ADD COLUMN meeting_id BIGINT REFERENCES meeting (id) ON DELETE SET NULL;

CREATE INDEX time_slot_meeting_idx ON time_slot (meeting_id);
